import {
  Profile,
  UserPreferences,
  Provider,
  ContentModule,
  ContentModuleVersion,
  CarePlan,
  CarePlanVersion,
  Handoff,
  ConsentRecord,
  UserAccount,
  ProfessionalAccount,
  SymptomEntry,
} from './types';
import { hashPassword } from '../auth/password';

// ─── Profiles ──────────────────────────────────────────────────────────────────

export const SEED_PROFILES: Profile[] = [
  {
    id: 'profile-ananya-sharma',
    displayName: 'Ananya Sharma',
    role: 'user',
    createdAt: new Date('2026-01-15T10:00:00.000Z'),
  },
  {
    id: 'profile-dr-maya-rao',
    displayName: 'Dr. Maya Rao',
    role: 'clinician',
    createdAt: new Date('2026-01-10T08:00:00.000Z'),
  },
  {
    id: 'profile-arjun-mehta',
    displayName: 'Arjun Mehta',
    role: 'user',
    createdAt: new Date('2026-02-01T12:00:00.000Z'),
  },
];

// ─── User Preferences ──────────────────────────────────────────────────────────

export const SEED_USER_PREFERENCES: UserPreferences[] = [
  {
    id: 'pref-ananya',
    userId: 'profile-ananya-sharma',
    language: 'hi-hinglish',
    mode: 'CONNECTED_CARE',
  },
  {
    id: 'pref-arjun',
    userId: 'profile-arjun-mehta',
    language: 'en',
    mode: 'GUEST',
  },
];

// ─── Auth Accounts (demo credentials; not production-grade hashing) ────────────

export const SEED_USER_ACCOUNTS: UserAccount[] = [
  {
    // Use the profile id as the account id so the authenticated session sub
    // matches seeded preferences, symptoms, and care plans in the demo.
    id: 'profile-ananya-sharma',
    email: 'ananya@example.com',
    passwordHash: hashPassword('password123'),
    displayName: 'Ananya Sharma',
    isAdultConfirmed: true,
    consentToContact: true,
    createdAt: new Date('2026-01-15T10:00:00.000Z'),
  },
];

export const SEED_PROFESSIONAL_ACCOUNTS: ProfessionalAccount[] = [
  {
    id: 'pro-account-maya',
    email: 'maya.rao@manas.demo',
    passwordHash: hashPassword('clinician123'),
    displayName: 'Dr. Maya Rao',
    providerId: 'provider-dr-maya-rao',
    role: 'clinician',
    createdAt: new Date('2026-01-10T08:00:00.000Z'),
  },
  {
    id: 'pro-account-vikram',
    email: 'vikram.singh@manas.demo',
    passwordHash: hashPassword('clinician123'),
    displayName: 'Dr. Vikram Singh',
    providerId: 'provider-dr-vikram-singh',
    role: 'clinician',
    createdAt: new Date('2026-01-12T08:00:00.000Z'),
  },
];

// ─── Providers (all isFictionalDemo: true) ─────────────────────────────────────

const SEED_PROVIDER_LIST: Provider[] = [
  {
    id: 'provider-aekta-brahmbhatt',
    profileId: 'profile-aekta-brahmbhatt',
    name: 'Aekta Brahmbhatt',
    title: 'Counsellor, Psychologist & Play Therapist',
    languages: ['English', 'Hindi'],
    focusAreas: ['play therapy', 'child & family wellbeing', 'anxiety', 'emotional regulation'],
    availability: 'Mon–Sat · 10 AM–6 PM IST',
    sessionType: 'Video + Chat',
    priceRange: '$70 – $100 per session',
    pricePerSession: 85,
    currency: 'USD',
    sessionDurationMinutes: 45,
    nextAvailable: 'Tomorrow · 10:30 AM IST',
    timezone: 'Asia/Kolkata',
    availabilityDays: 'Mon–Sat',
    availabilityStartHour: 10,
    availabilityEndHour: 18,
    nextAvailableDay: 'Tomorrow',
    nextAvailableHour: 10,
    nextAvailableMinute: 30,
    credentialsNote: 'Licensed Counsellor & Play Therapist',
    bio: 'Aekta Brahmbhatt is a counsellor and psychologist specialising in play therapy. She helps children and families express emotions, build resilience, and navigate stress through creative, age-appropriate techniques.',
    isFictionalDemo: true,
    isActualProfile: true,
  },
  {
    id: 'provider-dr-maya-rao',
    profileId: 'profile-dr-maya-rao',
    name: 'Dr. Maya Rao',
    title: 'Clinical Psychologist',
    languages: ['English', 'Hindi', 'Hinglish'],
    focusAreas: ['workplace stress', 'anxiety', 'burnout', 'mindfulness'],
    availability: 'Mon–Fri · 9 AM–5 PM IST',
    sessionType: 'Video + Chat',
    priceRange: '$95 – $125 per session',
    pricePerSession: 110,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Tomorrow · 10:00 AM IST',
    timezone: 'Asia/Kolkata',
    availabilityDays: 'Mon–Fri',
    availabilityStartHour: 9,
    availabilityEndHour: 17,
    nextAvailableDay: 'Tomorrow',
    nextAvailableHour: 10,
    credentialsNote: 'Licensed Clinical Psychologist — fictional demo provider',
    bio: 'Dr. Maya Rao is a clinical psychologist specialising in workplace wellbeing and burnout recovery. She uses a blend of CBT and mindfulness-based approaches.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-dr-vikram-singh',
    profileId: 'profile-dr-vikram-singh',
    name: 'Dr. Vikram Singh',
    title: 'Counselling Psychologist',
    languages: ['English', 'Hindi'],
    focusAreas: ['anxiety', 'depression', 'sleep disorders', 'life transitions'],
    availability: 'Tue–Sat · 10 AM–7 PM IST',
    sessionType: 'Video',
    priceRange: '$80 – $110 per session',
    pricePerSession: 95,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Friday · 2:00 PM IST',
    timezone: 'Asia/Kolkata',
    availabilityDays: 'Tue–Sat',
    availabilityStartHour: 10,
    availabilityEndHour: 19,
    nextAvailableDay: 'Friday',
    nextAvailableHour: 14,
    credentialsNote: 'Licensed Counselling Psychologist — fictional demo provider',
    bio: 'Dr. Vikram Singh is a counselling psychologist with over 10 years of experience helping adults navigate anxiety, sleep issues, and major life transitions.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-priya-kapoor',
    profileId: 'profile-priya-kapoor',
    name: 'Priya Kapoor',
    title: 'Wellness Coach & Mindfulness Facilitator',
    languages: ['English', 'Hinglish'],
    focusAreas: ['stress management', 'mindfulness', 'work-life balance', 'self-compassion'],
    availability: 'Mon–Thu · 6–9 PM IST',
    sessionType: 'Chat + Audio',
    priceRange: '$60 – $90 per session',
    pricePerSession: 75,
    currency: 'USD',
    sessionDurationMinutes: 45,
    nextAvailable: 'Saturday · 11:00 AM IST',
    timezone: 'Asia/Kolkata',
    availabilityDays: 'Mon–Thu',
    availabilityStartHour: 18,
    availabilityEndHour: 21,
    nextAvailableDay: 'Saturday',
    nextAvailableHour: 11,
    credentialsNote: 'Certified Wellness Coach — fictional demo provider',
    bio: 'Priya Kapoor is a certified wellness coach who facilitates mindfulness groups and one-to-one stress-management sessions for working professionals.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-dr-neha-iyer',
    profileId: 'profile-dr-neha-iyer',
    name: 'Dr. Neha Iyer',
    title: 'Psychiatrist & Psychotherapist',
    languages: ['English', 'Hindi', 'Tamil'],
    focusAreas: ['trauma', 'PTSD', 'chronic stress', 'somatic therapy'],
    availability: 'Wed–Sun · 11 AM–6 PM IST',
    sessionType: 'Video',
    priceRange: '$130 – $160 per session',
    pricePerSession: 145,
    currency: 'USD',
    sessionDurationMinutes: 60,
    nextAvailable: 'Wednesday · 12:30 PM IST',
    timezone: 'Asia/Kolkata',
    availabilityDays: 'Wed–Sun',
    availabilityStartHour: 11,
    availabilityEndHour: 18,
    nextAvailableDay: 'Wednesday',
    nextAvailableHour: 12,
    nextAvailableMinute: 30,
    credentialsNote: 'Board-Certified Psychiatrist — fictional demo provider',
    bio: 'Dr. Neha Iyer is a psychiatrist and psychotherapist with expertise in trauma-informed care and somatic experiencing. She offers integrative treatment plans.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-dr-tan-wei-lin',
    profileId: 'profile-dr-tan-wei-lin',
    name: 'Dr. Tan Wei Lin',
    title: 'Clinical Psychologist',
    languages: ['English', 'Mandarin'],
    focusAreas: ['anxiety', 'workplace stress', 'life transitions', 'perfectionism'],
    availability: 'Mon–Fri · 9 AM–6 PM SGT',
    sessionType: 'Video + Chat',
    priceRange: '$110 – $140 per session',
    pricePerSession: 125,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Tomorrow · 11:30 AM SGT',
    timezone: 'Asia/Singapore',
    availabilityDays: 'Mon–Fri',
    availabilityStartHour: 9,
    availabilityEndHour: 18,
    nextAvailableDay: 'Tomorrow',
    nextAvailableHour: 11,
    nextAvailableMinute: 30,
    credentialsNote: 'Registered Clinical Psychologist (Singapore) — fictional demo provider',
    bio: 'Dr. Tan Wei Lin is a Singapore-based clinical psychologist working with professionals on anxiety, perfectionism, and major life transitions. She conducts sessions in English and Mandarin (英语与普通话).',
    isFictionalDemo: true,
  },
  {
    id: 'provider-kavitha-selvam',
    profileId: 'profile-kavitha-selvam',
    name: 'Kavitha Selvam',
    title: 'Counselling Psychologist',
    languages: ['English', 'Tamil', 'Hindi'],
    focusAreas: ['family stress', 'cultural identity', 'anxiety', 'self-esteem'],
    availability: 'Tue–Sat · 10 AM–7 PM SGT',
    sessionType: 'Video',
    priceRange: '$85 – $115 per session',
    pricePerSession: 100,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Thursday · 4:00 PM SGT',
    timezone: 'Asia/Singapore',
    availabilityDays: 'Tue–Sat',
    availabilityStartHour: 10,
    availabilityEndHour: 19,
    nextAvailableDay: 'Thursday',
    nextAvailableHour: 16,
    credentialsNote: 'Registered Counsellor (Singapore) — fictional demo provider',
    bio: 'Kavitha Selvam supports adults navigating family expectations, cultural identity, and anxiety. She offers warm, strengths-based counselling in English, Tamil (தமிழ்), and Hindi.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-nurul-aisyah',
    profileId: 'profile-nurul-aisyah',
    name: 'Nurul Aisyah Rahman',
    title: 'Family Therapist & Counsellor',
    languages: ['English', 'Malay'],
    focusAreas: ['relationship stress', 'family wellbeing', 'grief', 'life transitions'],
    availability: 'Mon–Thu · 1–8 PM SGT',
    sessionType: 'Video + Chat',
    priceRange: '$80 – $105 per session',
    pricePerSession: 90,
    currency: 'USD',
    sessionDurationMinutes: 55,
    nextAvailable: 'Monday · 3:30 PM SGT',
    timezone: 'Asia/Singapore',
    availabilityDays: 'Mon–Thu',
    availabilityStartHour: 13,
    availabilityEndHour: 20,
    nextAvailableDay: 'Monday',
    nextAvailableHour: 15,
    nextAvailableMinute: 30,
    credentialsNote: 'Accredited Family Therapist (Singapore) — fictional demo provider',
    bio: 'Nurul Aisyah Rahman is a family therapist helping couples and households communicate with greater ease. Sessions are available in English and Bahasa Melayu.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-marcus-yeo',
    profileId: 'profile-marcus-yeo',
    name: 'Marcus Yeo',
    title: 'Wellbeing Coach',
    languages: ['English', 'Singlish'],
    focusAreas: ['stress management', 'work-life balance', 'burnout', 'habit change'],
    availability: 'Mon–Fri · 12 PM–9 PM SGT',
    sessionType: 'Chat + Audio',
    priceRange: '$55 – $80 per session',
    pricePerSession: 65,
    currency: 'USD',
    sessionDurationMinutes: 45,
    nextAvailable: 'Tomorrow · 6:00 PM SGT',
    timezone: 'Asia/Singapore',
    availabilityDays: 'Mon–Fri',
    availabilityStartHour: 12,
    availabilityEndHour: 21,
    nextAvailableDay: 'Tomorrow',
    nextAvailableHour: 18,
    credentialsNote: 'Certified Wellbeing Coach — fictional demo provider',
    bio: 'Marcus Yeo keeps things real and relaxed — practical coaching for busy Singaporeans who want straight answers, steady habits, and zero judgement. Sessions in English or Singlish, your choice.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-dr-emily-carter',
    profileId: 'profile-dr-emily-carter',
    name: 'Dr. Emily Carter',
    title: 'Health Psychologist',
    languages: ['English'],
    focusAreas: ['chronic stress', 'sleep disorders', 'burnout', 'mind-body health'],
    availability: 'Mon–Fri · 9 AM–5 PM EST',
    sessionType: 'Video',
    priceRange: '$120 – $150 per session',
    pricePerSession: 135,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Tomorrow · 9:00 AM EST',
    timezone: 'America/New_York',
    availabilityDays: 'Mon–Fri',
    availabilityStartHour: 9,
    availabilityEndHour: 17,
    nextAvailableDay: 'Tomorrow',
    nextAvailableHour: 9,
    credentialsNote: 'Licensed Health Psychologist (US) — fictional demo provider',
    bio: 'Dr. Emily Carter is a US-based health psychologist specialising in stress, sleep, and mind-body connection. She works with professionals across time zones via telehealth.',
    isFictionalDemo: true,
  },
  {
    id: 'provider-dr-sophie-whitmore',
    profileId: 'profile-dr-sophie-whitmore',
    name: 'Dr. Sophie Whitmore',
    title: 'Counselling Psychologist',
    languages: ['English'],
    focusAreas: ['anxiety', 'depression', 'life transitions', 'self-compassion'],
    availability: 'Mon–Fri · 9 AM–5 PM BST',
    sessionType: 'Video + Chat',
    priceRange: '$100 – $130 per session',
    pricePerSession: 115,
    currency: 'USD',
    sessionDurationMinutes: 50,
    nextAvailable: 'Friday · 10:30 AM BST',
    timezone: 'Europe/London',
    availabilityDays: 'Mon–Fri',
    availabilityStartHour: 9,
    availabilityEndHour: 17,
    nextAvailableDay: 'Friday',
    nextAvailableHour: 10,
    nextAvailableMinute: 30,
    credentialsNote: 'HCPC-Registered Psychologist (UK) — fictional demo provider',
    bio: 'Dr. Sophie Whitmore is a London-based counselling psychologist offering compassionate, evidence-based support for anxiety, low mood, and life transitions.',
    isFictionalDemo: true,
  },
];

/**
 * Curated directory order: the actual profile first, then a flagship English
 * profile, then Singapore's language diversity (Singlish, Mandarin, Malay,
 * Tamil), then Hindi-speaking profiles, then the remaining English-only ones.
 */
const PROVIDER_DISPLAY_ORDER = [
  'provider-aekta-brahmbhatt',
  'provider-dr-sophie-whitmore',
  'provider-marcus-yeo',
  'provider-dr-tan-wei-lin',
  'provider-nurul-aisyah',
  'provider-kavitha-selvam',
  'provider-dr-maya-rao',
  'provider-dr-vikram-singh',
  'provider-priya-kapoor',
  'provider-dr-neha-iyer',
  'provider-dr-emily-carter',
];

export const SEED_PROVIDERS: Provider[] = [...SEED_PROVIDER_LIST].sort(
  (a, b) => PROVIDER_DISPLAY_ORDER.indexOf(a.id) - PROVIDER_DISPLAY_ORDER.indexOf(b.id),
);

// ─── Content Modules ───────────────────────────────────────────────────────────

export const SEED_CONTENT_MODULES: ContentModule[] = [
  {
    id: 'module-pause-reflect',
    title: 'Pause and Reflect',
    purpose: 'A guided micro-exercise that helps the user slow down, notice their current state, and reflect on what they need right now.',
    status: 'DRAFT',
    currentVersionId: 'module-pause-reflect-v1',
    primaryLanguage: 'en',
  },
];

export const SEED_CONTENT_MODULE_VERSIONS: ContentModuleVersion[] = [
  {
    id: 'module-pause-reflect-v1',
    moduleId: 'module-pause-reflect',
    versionNumber: 1,
    steps: [
      {
        order: 1,
        instruction: 'Close your eyes or soften your gaze. Take three slow breaths.',
        durationSeconds: 30,
      },
      {
        order: 2,
        instruction: 'Notice what you are feeling in your body right now. Name it silently.',
        durationSeconds: 45,
      },
      {
        order: 3,
        instruction: 'Ask yourself: "What do I need most right now?" Sit with the answer for a moment.',
        durationSeconds: 60,
      },
      {
        order: 4,
        instruction: 'When you are ready, write one sentence about what came up for you.',
        durationSeconds: 120,
      },
    ],
    warnings: [
      'If you feel overwhelmed at any point, pause the exercise and take a break.',
      'This module is not a substitute for professional mental-health care.',
    ],
    contraindications: [
      'Active crisis or suicidal ideation — route to immediate resources instead.',
    ],
    escalationConditions: [
      'User reports feeling unsafe during the exercise.',
      'User reports dissociation or severe distress.',
    ],
    language: 'en',
    reviewStatus: 'DRAFT',
    translationStatus: 'PENDING',
  },
];

// ─── Care Plans ────────────────────────────────────────────────────────────────

export const SEED_CARE_PLANS: CarePlan[] = [
  {
    id: 'care-plan-ananya-001',
    userId: 'profile-ananya-sharma',
    clinicianId: 'provider-dr-maya-rao',
    status: 'ACTIVE',
    overallStatus: 'ACTIVE',
    activeVersionId: 'care-plan-ananya-001-v2',
    latestVersionId: 'care-plan-ananya-001-v2',
  },
];

export const SEED_CARE_PLAN_VERSIONS: CarePlanVersion[] = [
  {
    id: 'care-plan-ananya-001-v1',
    carePlanId: 'care-plan-ananya-001',
    versionNumber: 1,
    goals: [
      'Reduce work-related anxiety using structured reflection',
      'Improve sleep hygiene through nightly wind-down routine',
      'Build self-compassion practices for high-pressure days',
    ],
    assignedModules: ['module-pause-reflect'],
    checkInFrequency: 'twice_per_week',
    boundaries: {
      aiRole: 'facilitator',
      clinicianOversight: 'weekly_review',
      escalationPolicy: 'immediate_routing_to_crisis_resources_if_safety_flag',
    },
    followUpDate: new Date('2026-08-15T10:00:00.000Z'),
    status: 'COMPLETED',
    clinicianApprovedAt: new Date('2026-02-05T14:00:00.000Z'),
    userAcceptedAt: new Date('2026-02-06T09:30:00.000Z'),
    createdAt: new Date('2026-02-04T11:00:00.000Z'),
  },
  {
    id: 'care-plan-ananya-001-v2',
    carePlanId: 'care-plan-ananya-001',
    versionNumber: 2,
    goals: [
      'Deepen mindfulness practice with longer sessions',
      'Address workplace boundary-setting with manager',
      'Maintain sleep improvements achieved in V1',
      'Explore support-group participation',
    ],
    assignedModules: ['module-pause-reflect'],
    checkInFrequency: 'weekly',
    boundaries: {
      aiRole: 'facilitator',
      clinicianOversight: 'biweekly_review',
      escalationPolicy: 'immediate_routing_to_crisis_resources_if_safety_flag',
      v1Preserved: true,
    },
    followUpDate: new Date('2026-09-01T10:00:00.000Z'),
    status: 'ACTIVE',
    clinicianApprovedAt: new Date('2026-04-10T15:00:00.000Z'),
    userAcceptedAt: new Date('2026-04-11T10:00:00.000Z'),
    createdAt: new Date('2026-04-09T09:00:00.000Z'),
    previousVersionId: 'care-plan-ananya-001-v1',
  },
];

// ─── Handoffs ──────────────────────────────────────────────────────────────────

export const SEED_HANDOFFS: Handoff[] = [];

// ─── Consent Records ───────────────────────────────────────────────────────────

export const SEED_CONSENT_RECORDS: ConsentRecord[] = [];

// ─── Symptom Entries ───────────────────────────────────────────────────────────

export const SEED_SYMPTOM_ENTRIES: SymptomEntry[] = [
  {
    id: 'symptom-ananya-sleep-001',
    userId: 'profile-ananya-sharma',
    text: 'Trouble falling asleep before big work presentations',
    category: 'sleep',
    severity: 'moderate',
    frequency: 'weekly',
    impact: 'Affects energy and focus the next day',
    createdAt: new Date('2026-07-25T21:00:00.000Z'),
  },
  {
    id: 'symptom-ananya-sleep-002',
    userId: 'profile-ananya-sharma',
    text: 'Waking up at 3am and struggling to get back to sleep',
    category: 'sleep',
    severity: 'significant',
    frequency: 'several_times_a_week',
    impact: 'Leaves me tired during meetings',
    createdAt: new Date('2026-07-27T22:00:00.000Z'),
  },
  {
    id: 'symptom-ananya-stress-001',
    userId: 'profile-ananya-sharma',
    text: 'Tight shoulders and racing thoughts on deadline days',
    category: 'work_stress',
    severity: 'significant',
    frequency: 'several_times_a_week',
    impact: 'Makes it hard to unwind after work',
    createdAt: new Date('2026-07-28T19:30:00.000Z'),
  },
];
